### ISSUE TITLE
 Website Lacks Responsiveness on Various Devices

### ISSUE THREAD

**Issue by arshactually2** [hudy9x/namviek-landingpage#6]
The website does not respond properly when viewed on various devices, leading to a suboptimal user experience. Elements overlap, and some content becomes unreadable or inaccessible on smaller screens.

**Expected Behavior**
The website should adapt to various screen sizes without any overlap of elements or hidden content. Navigation should be smooth, and all text and interactive elements should be easily accessible.

**Actual Behavior**
Overlapping Elements: On screens smaller than 768px wide, the navigation bar overlaps with the website logo.
Hidden Content: On mobile devices (screens smaller than 480px wide), the footer content is cut off and not scrollable, hiding contact information.

**Steps to Reproduce**
1. Open the website in a desktop browser.
2. Use developer tools to switch to responsive mode.
3. Resize the view to the following widths: 768px, 480px.
4. Observe the issues as described in the Actual Behavior section.

![image](https://github.com/hudy9x/namviek-landingpage/assets/147138597/2bf9f60b-3149-46be-8e87-8db2c79b29e0)
![image](https://github.com/hudy9x/namviek-landingpage/assets/147138597/9c4a7ba7-f8ee-4f81-80ad-462e8f669f09)

**Additional Context**
These responsiveness issues may deter mobile users from effectively interacting with the website, potentially affecting user engagement and satisfaction.

**Comment by hudy9x** [comment]
@arshactually2 Appreciate that bro, thanks a lot
I'll review and merge it asap

**Comment by abhijain1705** [comment]
can I work on this?

**Comment by yesbhautik** [comment]
anyone working this?

**Comment by sskhan1** [comment]
@yesbhautik, or anyone still working on this issue? if No, I can work on this issue.

**Comment by hudy9x** [comment]
@sskhan1 
Actually I've been in charged of this issue. Cuz it's hard for me to detail requirements for the landing page.

**Comment by hudy9x** [comment]
working on it #10
